defaultSource: "file"           # for import of data and models
githubRepo: "data-tools"        # for import of models
mainFolder: "predefinedModels"  # for import of models
fileExtension: "datatools"      # for download of models
rPackageName: "DataTools"       # for download and import of models
