defaultSource: "file"           # for import of data and models
# file types that are allowed for import from Pandora ("ckan")
ckanFileTypes:
  - "xls"
  - "xlsx"
  - "csv"
  - "odt"
  - "txt"
ckanModelTypes:
  - "zip"
  - "datatools"
githubRepo: "data-tools"        # for import of models
fileExtension: "datatools"      # for download of models
rPackageName: "DataTools"       # for download and import of models
# settings to load remote (online) example zips or models or data links:
remoteModelsSpecs:
  zip:
    folder: "exampleZip"
  model:
    folder: "predefinedModels"
  data:
    folder: "dataQueries"
githubMapping:
  # internal apps
  BMSCApp: "bmsc-app"
  DataTools: "data-tools"
  mpiBpred: "bpred"
  MpiIsoApp: "iso-app"
  BMSC-S: "BMSC-S" # updated name
  Bpred: "Bpred"   # updated name
  OsteoBioR: "OsteoBioR"
  PlotR: "PlotR"
  ReSources: "ReSources"
  MapR: "MapR"
  DSSM: "DSSM"     # updated name
  # external apps
  CausalR: "causalr"
