# General Settings ################
#
# Following settings can be defined app specific in the config.yaml file of the respective app
defaultSource: "file"           # for import of data and models
# file types that are allowed for import from Pandora ("ckan")
ckanFileTypes:
  - "xls"
  - "xlsx"
  - "csv"
  - "odt"
  - "txt"
ckanModelTypes:
  - "zip"
  - "datatools"
githubRepo: "data-tools"        # for import of models
fileExtension: "datatools"      # for download of models
rPackageName: "DataTools"       # for download and import of models
#
# Internal Settings ################
#
# Following settings are internal and specific only for the package DataTools
# settings to load remote (online) example zips or models or data links:
remoteModelsSpecs:
  zip:
    folder: "exampleZip"
  model:
    folder: "predefinedModels"
  data:
    folder: "dataQueries"
githubMapping:
  # internal apps
  BMSCApp: "bmsc-app"
  DataTools: "data-tools"
  mpiBpred: "bpred"
  MpiIsoApp: "iso-app"
  BMSCS: "BMSCS" # updated name
  Bpred: "Bpred"   # updated name
  OsteoBioR: "OsteoBioR"
  PlotR: "PlotR"
  ReSources: "ReSources"
  MapR: "MapR"
  DSSM: "DSSM"     # updated name
  TraceR: "TraceR"
  # external apps
  CausalR: "causalr"
packageMapping: # we do need this for checks in model imports
  # mapping to former names of the packages
  DSSM: "MpiIsoApp"
  BMSCS: "BMSCApp"
  Bpred: "mpiBpred"
  # here names did not change
  DataTools: "DataTools"
  OsteoBioR: "OsteoBioR"
  PlotR: "PlotR"
  ReSources: "ReSources"
  MapR: "MapR"
  TraceR: "TraceR"
  CausalR: "CausalR"
